FROM node:10-alpine

WORKDIR /
COPY package.json .
RUN npm install
COPY . .
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV
ENV PATH="$PATH:/.etc"
EXPOSE 80
# RUN npm prune --production
CMD npm start
