name: Local Server Docker Run

on:
  push:
    branches:
      - master
  release:
    types: [created]
  workflow_dispatch: # Put here!!
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.development
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/imcworkflownode:latest
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: imcmaster.iptime.org
          user: root
          port: 7070
          pass: ykn9080
          run: |
            echo docker create port:8011 name:imcworkflownode 으로 작업합니다...
            echo
            echo 1/5 docker login 
            echo ...이미설정되있는걸로 알고 pass
            wait
            echo 2/5 docker pull
            docker pull yknam/imcworkflownode
            wait
            echo 3/5 이전 버젼 삭제후 docker run
            docker rm -f imcworkflownode
            wait
            docker run --name imcworkflownode --network kong-net -p 8011:8011 -d yknam/imcworkflownode
            wait
            echo 4/5 docker image prune
            docker image prune -f
            wait
            echo 5/5 finished.  see at http://imcmaster.iptime.org:8011
